# Generated by Django 4.0.6 on 2023-02-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontaxing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carbonCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100)),
                ('cap_alloted', models.IntegerField()),
            ],
        ),
    ]
