# Generated by Django 4.0.6 on 2023-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontaxing_app', '0002_carboncap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonemmited',
            name='carbon_emmited',
        ),
        migrations.AddField(
            model_name='carbonemmited',
            name='carbon_emmited_CH4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carbonemmited',
            name='carbon_emmited_CO2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carbonemmited',
            name='carbon_emmited_F',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carbonemmited',
            name='carbon_emmited_N2O',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carbonemmited',
            name='carbon_emmited_Total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carbonemmited',
            name='public_key',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbonemmited',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
